blank_issues_enabled: false
contact_links:
  - name: 🔒️ Security Issue
    url: https://typo3.org/community/teams/security
    about: If you encounter a security issue 👿, please reach out **only** to the TYPO3 Security Team by writing to security (at) typo3.org. Please don't share the information with the extension author or anyone else.
