services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brotkrueml\MatomoWidgets\:
    resource: '../Classes/*'

  cache.matomo_widgets:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments:
      $identifier: 'matomo_widgets'

  Brotkrueml\MatomoWidgets\Domain\Repository\CachingRepositoryDecorator:
    arguments:
      $repository: '@Brotkrueml\MatomoWidgets\Domain\Repository\MatomoRepository'
      $cache: '@cache.matomo_widgets'

  Brotkrueml\MatomoWidgets\Domain\Repository\RepositoryInterface: '@Brotkrueml\MatomoWidgets\Domain\Repository\CachingRepositoryDecorator'

  dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.actionsPerDay:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\GenericBarChartDataProvider'
    arguments:
      $method: VisitsSummary.getActions
      $barLabel: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.actions.dataset.label'
      $barColour: '#4c7e3a'
      $parameters:
        period: day
        date: last28

  dashboard.widget.brotkrueml.matomo_widgets.visitsSummary.actionsPerDay:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $dataProvider: '@dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.actionsPerDay'
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.visitsSummary.actionsPerDay'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.actionsPerDay.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.actionsPerDay.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'medium'

  dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.actionsPerMonth:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\GenericBarChartDataProvider'
    arguments:
      $method: VisitsSummary.getActions
      $barLabel: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.actions.dataset.label'
      $barColour: '#4c7e3a'
      $parameters:
        period: month
        date: last12

  dashboard.widget.brotkrueml.matomo_widgets.visitsSummary.actionsPerMonth:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $dataProvider: '@dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.actionsPerMonth'
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.visitsSummary.actionsPerMonth'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.actionsPerMonth.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.actionsPerMonth.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'small'

  dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.visitsPerDay:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\GenericBarChartDataProvider'
    arguments:
      $method: VisitsSummary.getVisits
      $barLabel: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.visits.dataset.label'
      $barColour: '#1a568f'
      $parameters:
        period: day
        date: last28

  dashboard.widget.brotkrueml.matomo_widgets.visitsSummary.visitsPerDay:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $dataProvider: '@dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.visitsPerDay'
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.visitsSummary.visitsPerDay'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.visitsPerDay.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.visitsPerDay.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'medium'

  dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.visitsPerMonth:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\GenericBarChartDataProvider'
    arguments:
      $method: VisitsSummary.getVisits
      $barLabel: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.visits.dataset.label'
      $barColour: '#1a568f'
      $parameters:
        period: month
        date: last12

  dashboard.widget.brotkrueml.matomo_widgets.visitsSummary.visitsPerMonth:
    class: 'TYPO3\CMS\Dashboard\Widgets\BarChartWidget'
    arguments:
      $dataProvider: '@dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.visitsPerMonth'
      $view: '@dashboard.views.widget'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.visitsSummary.visitsPerMonth'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.visitsPerMonth.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.visitsPerMonth.description'
        iconIdentifier: 'content-widget-chart-bar'
        height: 'medium'
        width: 'small'

  dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.bounceRate:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\GenericValueDataProvider'
    arguments:
      $method: VisitsSummary.get
      $columnName: bounce_rate
      $parameters:
        period: month
        date: today

  dashboard.widget.brotkrueml.matomo_widgets.visitsSummary.bounceRate:
    class: 'Brotkrueml\MatomoWidgets\Widgets\ValueWithIconWidget'
    arguments:
      $dataProvider: '@dashboard.provider.brotkrueml.matomo_widgets.visitsSummary.bounceRate'
      $view: '@dashboard.views.widget'
      $options:
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.bounceRate.title'
        subtitle: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.bounceRate.subtitle'
        icon: 'content-target'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.visitsSummary.bounceRate'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.bounceRate.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.visitsSummary.bounceRate.description'
        iconIdentifier: 'content-widget-number'

  dashboard.provider.brotkrueml.matomo_widgets.devicesDetection.browsers:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\GenericDoughnutChartDataProvider'
    arguments:
      $method: DevicesDetection.getBrowsers
      $labelColumn: label
      $valueColumn: nb_visits
      $limit: 7
      $parameters:
        period: month
        date: today
        filter_sort_column: nb_visits
        filter_sort_order: desc

  dashboard.widget.brotkrueml.matomo_widgets.devicesDetection.browsers:
    class: 'TYPO3\CMS\Dashboard\Widgets\DoughnutChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@dashboard.provider.brotkrueml.matomo_widgets.devicesDetection.browsers'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.devicesDetection.browsers'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.devicesDetection.browsers.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.devicesDetection.browsers.description'
        iconIdentifier: 'content-widget-chart-pie'
        height: 'medium'
        width: 'small'

  dashboard.provider.brotkrueml.matomo_widgets.devicesDetection.osFamilies:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\GenericDoughnutChartDataProvider'
    arguments:
      $method: DevicesDetection.getOsFamilies
      $labelColumn: label
      $valueColumn: nb_visits
      $limit: 5
      $parameters:
        period: month
        date: today
        filter_sort_column: nb_visits
        filter_sort_order: desc

  dashboard.widget.brotkrueml.matomo_widgets.devicesDetection.osFamilies:
    class: 'TYPO3\CMS\Dashboard\Widgets\DoughnutChartWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@dashboard.provider.brotkrueml.matomo_widgets.devicesDetection.osFamilies'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.devicesDetection.osFamilies'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.devicesDetection.osFamilies.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.devicesDetection.osFamilies.description'
        iconIdentifier: 'content-widget-chart-pie'
        height: 'medium'
        width: 'small'

  dashboard.provider.brotkrueml.matomo_widgets.referrers.campaigns:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\GenericTableDataProvider'
    arguments:
      $method: Referrers.getCampaigns
      $columns:
        - column: label
          header: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.referrers.campaigns.column.name'
        - column: nb_visits
          header: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.referrers.campaigns.column.visits'
          align: text-right
      $parameters:
        period: month
        date: today
        filter_limit: 30
        filter_sort_column: nb_visits
        filter_sort_order: desc

  dashboard.widget.brotkrueml.matomo_widgets.referrers.campaigns:
    class: 'Brotkrueml\MatomoWidgets\Widgets\TableWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $dataProvider: '@dashboard.provider.brotkrueml.matomo_widgets.referrers.campaigns'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.referrers.campaigns'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.referrers.campaigns.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.referrers.campaigns.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'small'

  dashboard.buttons.brotkrueml.matomo_widgets.linkMatomo:
    class: 'Brotkrueml\MatomoWidgets\Widgets\Provider\LinkMatomoButtonProvider'

  dashboard.widget.brotkrueml.matomo_widgets.linkMatomo:
    class: 'TYPO3\CMS\Dashboard\Widgets\CtaWidget'
    arguments:
      $view: '@dashboard.views.widget'
      $buttonProvider: '@dashboard.buttons.brotkrueml.matomo_widgets.linkMatomo'
      $options:
        text: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.linkMatomo.text'
    tags:
      - name: dashboard.widget
        identifier: 'matomo_widgets.linkMatomo'
        groupNames: 'matomo'
        title: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.linkMatomo.title'
        description: 'LLL:EXT:matomo_widgets/Resources/Private/Language/Dashboard.xlf:widgets.linkMatomo.description'
        iconIdentifier: 'content-widget-text'
        height: 'small'
        width: 'small'
