name: Documentation

on:
  push:
    paths:
      - 'Documentation/**'
  pull_request:
    paths:
      - 'Documentation/**'


jobs:
  tests:
    name: Rendering
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Documentation renders without warnings
        run: |
          make docs-check
